settings:
  legacy:
    force: false
    interval: 0s
schema:
  - name: app
    path: .
    commands:
      install:
        status: true
        method: go build -o bin/line-notify src/cmd/main.go
      run:
        status: true
        method: ./bin/line-notify
    watcher:
      extensions:
        - go
      paths:
        - /
      ignored_paths:
        - .git
        - .realize
        - vendor
